"""empty message

Revision ID: fb94269c4fa8
Revises: 5957651796f9
Create Date: 2021-03-29 11:57:01.534608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb94269c4fa8'
down_revision = '5957651796f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rss_feed_url', sa.Text(), nullable=False),
    sa.Column('aws_url', sa.Text(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws')
    # ### end Alembic commands ###
